# -*- coding: utf-8 -*-
"""CADL2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YERF24ELtMx0bgdrljX9lTTxqlN4ZqGC
"""

#CADL2: Feature Extraction
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IMDB Dataset.csv")

# Preview
print(df.head())

# Take a sample of 10 reviews for quick testing
docs = df['review'].sample(10, random_state=42).tolist()

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Bag of Words
print("🔹 Bag of Words Representation")
vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(docs)
print(vectorizer.get_feature_names_out())
print(X_bow.toarray())

# TF-IDF
print("\n🔹 TF-IDF Representation")
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(docs)
print(tfidf.get_feature_names_out())
print(X_tfidf.toarray())